#!/bin/zsh
is_macos() {
  [[ "$(uname -s)" == "Darwin" ]]
}

if is_macos; then
    # reset launchpad
    defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock

    # .DS_Store
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE
fi
